window.JOBS = [
  {id:'cdb-hb',category:'银行',org:'国家开发银行',region:'湖北·武汉',role:'湖北省分行－经济金融类',level:'冲刺',core:true,deadline:'10/7 24:00',url:'https://cdb2027.zhaopin.com',keyword:'经济金融类',note:'政策性银行；专业匹配度高'},
  {id:'psbc-hb',category:'银行',org:'邮储银行',region:'湖北',role:'湖北省分行－U培生（经营管理）',level:'主投',core:true,deadline:'10/7 24:00',url:'https://psbc2027.zhaopin.com',keyword:'U培生 经营管理 湖北',note:'邮储最多申报2个岗位'},
  {id:'psbc-zj',category:'银行',org:'邮储银行',region:'浙江',role:'浙江省分行－U培生（经营管理）',level:'主投',core:false,deadline:'10/7 24:00',url:'https://psbc2027.zhaopin.com',keyword:'U培生 经营管理 浙江',note:'与湖北U培组成地域组合'},
  {id:'spdb-hz',category:'银行',org:'浦发银行',region:'浙江·杭州',role:'杭州分行－管理培训生',level:'冲刺',core:false,deadline:'10/8 18:00',url:'https://job.spdb.com.cn',keyword:'杭州分行 管理培训生',note:'热门地区'},
  {id:'spdb-xa',category:'银行',org:'浦发银行',region:'陕西·西安',role:'西安分行－管理培训生',level:'主投',core:true,deadline:'10/8 18:00',url:'https://job.spdb.com.cn',keyword:'西安分行 管理培训生',note:'建议与杭州组成浦发两机构组合'},
  {id:'ccb-js',category:'银行',org:'建设银行',region:'江苏',role:'江苏省分行－管理培训生（通用方向）',level:'冲刺',core:false,deadline:'10/8 24:00',url:'https://job.ccb.com',keyword:'江苏省分行 管理培训生 通用',note:'建行最多2个志愿'},
  {id:'ccb-hb',category:'银行',org:'建设银行',region:'湖北',role:'湖北省分行－客户经理岗',level:'稳妥',core:true,deadline:'10/8 24:00',url:'https://job.ccb.com',keyword:'湖北省分行 客户经理',note:'建议作为建行稳妥志愿'},
  {id:'icbc-zj',category:'银行',org:'工商银行',region:'浙江',role:'浙江省分行－专业英才',level:'主投',core:true,deadline:'10/8（以系统为准）',url:'https://job.icbc.com.cn/pc/index.html',keyword:'浙江省分行 专业英才',note:'比纯管培更贴合经济学+数据分析背景'},
  {id:'icbc-he',category:'银行',org:'工商银行',region:'河北',role:'河北省分行－星辰管培生',level:'主投',core:false,deadline:'10/8（以系统为准）',url:'https://job.icbc.com.cn/pc/index.html',keyword:'河北省分行 星辰管培生',note:'扩大上岸概率'},
  {id:'icbc-gs',category:'银行',org:'工商银行',region:'甘肃',role:'甘肃省分行－星辰管培生',level:'稳妥',core:false,deadline:'10/8（以系统为准）',url:'https://job.icbc.com.cn/pc/index.html',keyword:'甘肃省分行 星辰管培生',note:'备用地区'},
  {id:'boc-zj',category:'银行',org:'中国银行',region:'浙江',role:'浙江省分行－管理培训生',level:'冲刺',core:false,deadline:'10/9 24:00',url:'https://campus.chinahr.com/pages/2027-boc',keyword:'浙江省分行 管理培训生',note:'中行5岗之一'},
  {id:'boc-js',category:'银行',org:'中国银行',region:'江苏',role:'江苏省分行－管理培训生',level:'冲刺',core:false,deadline:'10/9 24:00',url:'https://campus.chinahr.com/pages/2027-boc',keyword:'江苏省分行 管理培训生',note:'中行5岗之一'},
  {id:'boc-hb',category:'银行',org:'中国银行',region:'湖北',role:'湖北省分行－管理培训生',level:'主投',core:true,deadline:'10/9 24:00',url:'https://campus.chinahr.com/pages/2027-boc',keyword:'湖北省分行 管理培训生',note:'核心主投'},
  {id:'boc-sx',category:'银行',org:'中国银行',region:'陕西',role:'陕西省分行－管理培训生',level:'主投',core:true,deadline:'10/9 24:00',url:'https://campus.chinahr.com/pages/2027-boc',keyword:'陕西省分行 管理培训生',note:'核心主投'},
  {id:'boc-hn',category:'银行',org:'中国银行',region:'河南',role:'河南省分行－管理培训生',level:'主投',core:true,deadline:'10/9 24:00',url:'https://campus.chinahr.com/pages/2027-boc',keyword:'河南省分行 管理培训生',note:'核心主投'},
  {id:'cmb-hz',category:'银行',org:'招商银行',region:'浙江·杭州',role:'杭州分行－定向培养生',level:'冲刺',core:false,deadline:'10/10',url:'https://career.cmbchina.com',keyword:'杭州分行 定向培养生',note:'热门地区'},
  {id:'cmb-nj',category:'银行',org:'招商银行',region:'江苏·南京',role:'南京分行－定向培养生',level:'冲刺',core:false,deadline:'10/10',url:'https://career.cmbchina.com',keyword:'南京分行 定向培养生',note:'与你学历和CET-6匹配'},
  {id:'cmb-wh',category:'银行',org:'招商银行',region:'湖北·武汉',role:'武汉分行－定向培养生',level:'主投',core:true,deadline:'10/10 23:59',url:'https://career.cmbchina.com',keyword:'武汉分行 定向培养生',note:'核心主投'},
  {id:'cmb-xa',category:'银行',org:'招商银行',region:'陕西·西安',role:'西安分行－定向培养类',level:'主投',core:true,deadline:'10/10',url:'https://career.cmbchina.com',keyword:'西安分行 定向培养',note:'关注公司/风险/职能等培养方向'},
  {id:'cmb-zz',category:'银行',org:'招商银行',region:'河南·郑州',role:'郑州分行－定向培养生',level:'主投',core:false,deadline:'10/10',url:'https://career.cmbchina.com',keyword:'郑州分行 定向培养生',note:'郑州重点岗位'},
  {id:'adbc-hb',category:'银行',org:'农业发展银行',region:'湖北',role:'湖北省分行－经济金融/信贷相关岗',level:'主投',core:true,deadline:'10/11 24:00',url:'https://campus.chinahr.com/pages/adbc2027/',keyword:'湖北 经济金融 信贷',note:'优先省级或二级分行本级；注意英语分数条件'},
  {id:'adbc-js',category:'银行',org:'农业发展银行',region:'江苏',role:'江苏省分行－经济金融/信贷相关岗',level:'主投',core:false,deadline:'10/11 24:00',url:'https://campus.chinahr.com/pages/adbc2027/',keyword:'江苏 经济金融 信贷',note:'农发行最多2个岗位；同一省级分行限1岗'},
  {id:'czbank-hq',category:'银行',org:'浙商银行',region:'浙江·杭州',role:'总行－综合培养岗',level:'主投',core:true,deadline:'10/25',url:'https://zp.czbank.com.cn',keyword:'总行 综合培养岗',note:'总行储备干部/业务骨干方向'},
  {id:'cib-hq',category:'银行',org:'兴业银行',region:'总行',role:'管理培训生－综合方向',level:'冲刺',core:false,deadline:'10/25',url:'https://job.cib.com.cn/',keyword:'管理培训生 综合方向',note:'经济、金融、国际贸易等专业更匹配'},

  {id:'cnpc-eri-energy',category:'国央企',org:'中石油经济技术研究院',region:'北京',role:'能源市场研究',level:'S+',core:true,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'经济技术研究院 能源市场研究',note:'专业直接包含产业经济学；硕士可报；与论文、计量分析、行业研究高度匹配'},
  {id:'cnpc-intl-trade',category:'国央企',org:'中石油国际事业公司',region:'北京/海外',role:'国际贸易',level:'S',core:true,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'国际事业 国际贸易',note:'本科贸易经济 + 硕士产业经济，国际业务方向匹配'},
  {id:'cnpc-liaohe-mgmt',category:'国央企',org:'中石油辽河油田',region:'辽宁',role:'财务与企业管理',level:'S',core:true,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'辽河油田 企业管理',note:'专业明确包含产业经济学；相对稳妥'},
  {id:'sinopec-south-sales',category:'国央企',org:'中石化化工销售华南',region:'广州/华南',role:'营销客户代表',level:'S',core:true,deadline:'待核实',url:'https://job.sinopec.com/',keyword:'化工销售华南 营销客户代表',note:'产业经济学可报；经营数据/客户沟通/合同订单经历高度匹配'},
  {id:'cssc-gsi-business',category:'国央企',org:'中国船舶广船国际',region:'广州',role:'商务经营',level:'S',core:true,deadline:'待核实',url:'https://cssc.zhaopin.com/job/index.html',keyword:'广船国际 商务 经营',note:'已有中国船舶725所经营部实习，体系内求职逻辑自然'},
  {id:'cnpc-hubei-retail',category:'国央企',org:'中石油湖北销售',region:'湖北',role:'新零售运营',level:'S',core:true,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'湖北销售 新零售',note:'应用经济学方向可报；偏经营、运营和数据分析'},
  {id:'cnpc-chongqing-plan',category:'国央企',org:'中石油重庆销售',region:'重庆',role:'运营规划',level:'A+',core:false,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'重庆销售 运营规划',note:'偏经营规划；产业经济学属于应用经济学'},
  {id:'cnpc-east-trade',category:'国央企',org:'中石油国际事业华东公司',region:'上海/海外',role:'国际贸易',level:'A+',core:false,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'国际事业 华东 国际贸易',note:'本科贸易经济优势明显'},
  {id:'cnodc-business',category:'国央企',org:'中石油国际勘探开发',region:'北京/海外',role:'国际商务',level:'A+',core:false,deadline:'待核实',url:'https://zhaopin.cnpc.com.cn/',keyword:'国际勘探开发 商务',note:'经济学/应用经济学/技术经济等方向可报；平台好、竞争高'},
  {id:'cosco-special-ops',category:'国央企',org:'中远海运特运',region:'广州',role:'航运经营',level:'A+',core:true,deadline:'待核实',url:'https://coscoshipping.iguopin.com/',keyword:'中远海运特运 航运经营',note:'贸易经济 + 产业经济，和航运经营场景高度适配'},
  {id:'sinomach-trade',category:'国央企',org:'国机集团',region:'北京等',role:'贸易业务管理/经济管理类',level:'A+',core:true,deadline:'待核实',url:'https://zhaopin.sinomach.com.cn/',keyword:'贸易 经营 经济',note:'贸易、产业、经营背景匹配'},
  {id:'cscec1-invest',category:'国央企',org:'中建一局集团建设发展',region:'全国',role:'投资业务',level:'A+',core:true,deadline:'待核实',url:'https://recruit.cscec.com/',keyword:'中建一局集团建设发展 投资',note:'可突出产业研究、商业模式、项目评价能力'},
  {id:'cscec1-operation',category:'国央企',org:'中建一局集团建设发展',region:'全国',role:'运营业务',level:'A',core:false,deadline:'待核实',url:'https://recruit.cscec.com/',keyword:'中建一局集团建设发展 运营',note:'应用经济学可报；偏项目运营、资产运营和经营分析'},
  {id:'cscec2-invest',category:'国央企',org:'中建二局',region:'全国',role:'投资运营/金融投资类',level:'A',core:false,deadline:'待核实',url:'https://recruit.cscec.com/',keyword:'中建二局 投资',note:'部分岗位专业直接出现产业经济学'},
  {id:'cssc-gsi-mgmt',category:'国央企',org:'中国船舶广船国际',region:'广州',role:'企业管理',level:'A',core:false,deadline:'待核实',url:'https://cssc.zhaopin.com/job/index.html',keyword:'广船国际 企业管理',note:'可结合725所经营部实习；适合战略、供应链、企业经营'},
  {id:'cosco-fuel',category:'国央企',org:'中远海运特运',region:'广州',role:'燃油采购',level:'A',core:false,deadline:'待核实',url:'https://coscoshipping.iguopin.com/',keyword:'中远海运特运 燃油采购',note:'经济与贸易类可报；本科贸易经济匹配'},
  {id:'cosco-mgmt',category:'国央企',org:'中远海运特运',region:'广州',role:'企业管理',level:'A',core:false,deadline:'待核实',url:'https://coscoshipping.iguopin.com/',keyword:'中远海运特运 企业管理',note:'中高匹配'},
  {id:'sinopec-4-intl',category:'国央企',org:'中石化第四建设',region:'天津/项目地',role:'国际经营',level:'A',core:false,deadline:'待核实',url:'https://job.sinopec.com/',keyword:'第四建设 国际经营',note:'应用经济、国际经贸、技术经济等可报'},
  {id:'sinopec-north-mgmt',category:'国央企',org:'中石化华北石油局',region:'河南/陕西/内蒙古/甘肃/宁夏等',role:'综合管理',level:'A-',core:false,deadline:'待核实',url:'https://job.sinopec.com/',keyword:'华北石油局 综合管理',note:'专业明确包含应用经济学/产业经济学；地域较广'},
  {id:'huaneng-econ',category:'国央企',org:'中国华能',region:'全国',role:'经济/经营/财务管理类',level:'A-',core:false,deadline:'待核实',url:'https://zhaopin.chng.com.cn/',keyword:'经济 经营 财务',note:'重点看普通校招岗位，不必强求总部专项'},
  {id:'cgn-newenergy',category:'国央企',org:'中广核新能源',region:'北京/天津/吉林/山东等',role:'经济/经营管理类',level:'A-',core:true,deadline:'待核实',url:'https://cgn.hotjob.cn/',keyword:'新能源 经营 市场 投资',note:'重点筛经营、市场、投资、计划、项目开发'},
  {id:'dongfeng-business',category:'国央企',org:'东风汽车',region:'武汉等',role:'综合职能/经营类',level:'A-',core:false,deadline:'待核实',url:'https://app.mokahr.com/m/campus-recruitment/dfmc/164438#/home',keyword:'经营 营销 运营 职能',note:'武汉地区扩充岗位'},
  {id:'sinopec-zhongyuan',category:'国央企',org:'中石化中原石油工程',region:'河南/国内外项目地',role:'综合管理',level:'B+',core:false,deadline:'待核实',url:'https://job.sinopec.com/',keyword:'中原石油工程 综合管理',note:'中等匹配，适合扩充Offer池'},
  {id:'sinopec-nw',category:'国央企',org:'中石化西北油田',region:'新疆等',role:'综合管理',level:'B+',core:false,deadline:'待核实',url:'https://job.sinopec.com/',keyword:'西北油田 综合管理',note:'中等匹配，地域需接受'},
  {id:'cmcc-beijing',category:'国央企',org:'北京移动',region:'北京',role:'经营分析/市场运营类',level:'B+',core:false,deadline:'待核实',url:'https://job.10086.cn/',keyword:'北京公司 经营分析',note:'数据分析、经营分析能力可迁移'},
  {id:'cmcc-internet',category:'国央企',org:'中移互联网',region:'广州',role:'经营分析',level:'B+',core:false,deadline:'待核实',url:'https://job.10086.cn/',keyword:'中移互联网 经营分析',note:'市场数据/行业竞品分析，Stata/Python可用'},
  {id:'unicom-liaoning',category:'国央企',org:'辽宁联通',region:'辽宁',role:'市场营销/经营类',level:'B',core:false,deadline:'待核实',url:'https://zglt.zhaopin.com/',keyword:'辽宁省分公司 市场 经营',note:'东北地区扩充Offer池'},
  {id:'chnenergy-industry',category:'国央企',org:'国家能源集团',region:'北京',role:'总部职能部门－通用管理岗（产业研究）',level:'冲刺',core:true,deadline:'紧急核实',url:'https://zhaopin.chnenergy.com.cn/',keyword:'产业研究',note:'每人通常只能选1个岗位；投递前先横向比较所有可报经济管理岗'},
  {id:'cnooc-pool',category:'国央企',org:'中国海油',region:'多地',role:'岗位池：市场开发/国际商务/经营管理/规划投资/新能源运营/综合管理',level:'待筛',core:true,deadline:'待核实',url:'https://cnooc.zhaopin.com/',keyword:'市场开发 国际商务 经营管理 规划投资 新能源运营 综合管理',note:'重点看中国海油国际、国际贸易、气电集团、北京新能源、炼化公司等'},
  {id:'huadian-regular',category:'国央企',org:'中国华电',region:'全国',role:'普通校招：经营管理/经济管理/市场/计划',level:'待筛',core:false,deadline:'待核实',url:'https://www.chd.com.cn/col/col1087/index.html',keyword:'经营管理 经济管理 市场 计划',note:'不主攻“青年骏才”；优先普通校招/蓝海项目'},
  {id:'datang-regular',category:'国央企',org:'中国大唐',region:'全国',role:'普通校招：技术经济/电力营销/经营管理/计划发展',level:'待筛',core:false,deadline:'待核实',url:'https://www.cdtrczp.com/',keyword:'技术经济 电力营销 经营管理 计划发展',note:'不建议在京二级单位本部管培专项'}
];
